### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#347] opened 2023-05-16 18:52 UTC
When starting Movary as a docker container, the following errors appear in the logs:

```
2023-05-16 18:49:59,566 INFO spawned: 'movary' with pid 90
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imagick.so (Error loading shared library libgomp.so.1: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imagick.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imagick.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imagick.so.so: No such file or directory)) in Unknown on line 0
PHP Fatal error:  Uncaught RuntimeException: Not supported database mode: "mysql" in /app/src/Factory.php:144
Stack trace:
#0 [internal function]: Movary\Factory::createDbConnection(Object(Movary\ValueObject\Config))
#1 /app/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Array, Array)
#2 /app/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(69): Invoker\Invoker->call(Array, Array)
#3 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array)
#4 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition), Array)
#5 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\FactoryDefinition))
#6 /app/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\Container->get('Doctrine\\DBAL\\C...')
#7 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(55): DI\Definition\Reference->resolve(Object(DI\Container))
#8 /app/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\Reference))
#9 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(123): DI\Definition\Resolver\ParameterResolver->resolveParameters(Object(DI\Definition\ObjectDefinition\MethodInjection), Object(ReflectionMethod), Array)
#10 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#11 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#12 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#13 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#14 /app/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\Container->get('Movary\\Api\\Trak...')
#15 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(55): DI\Definition\Reference->resolve(Object(DI\Container))
#16 /app/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\Reference))
#17 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(123): DI\Definition\Resolver\ParameterResolver->resolveParameters(Object(DI\Definition\ObjectDefinition\MethodInjection), Object(ReflectionMethod), Array)
#18 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#19 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#20 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#21 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#22 /app/src/Factory.php(274): DI\Container->get('Movary\\Api\\Trak...')
#23 [internal function]: Movary\Factory::createTraktApi(Object(DI\Container))
#24 /app/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Array, Array)
#25 /app/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(69): Invoker\Invoker->call(Array, Array)
#26 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array)
#27 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition), Array)
#28 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\FactoryDefinition))
#29 /app/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\Container->get('Movary\\Api\\Trak...')
#30 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(55): DI\Definition\Reference->resolve(Object(DI\Container))
#31 /app/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\Reference))
#32 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(123): DI\Definition\Resolver\ParameterResolver->resolveParameters(Object(DI\Definition\ObjectDefinition\MethodInjection), Object(ReflectionMethod), Array)
#33 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#34 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#35 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#36 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#37 /app/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\Container->get('Movary\\Service\\...')
#38 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(55): DI\Definition\Reference->resolve(Object(DI\Container))
#39 /app/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\Reference))
#40 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(123): DI\Definition\Resolver\ParameterResolver->resolveParameters(Object(DI\Definition\ObjectDefinition\MethodInjection), Object(ReflectionMethod), Array)
#41 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#42 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#43 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#44 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#45 /app/bin/console.php(7): DI\Container->get('Movary\\Command\\...')
#46 {main}
  thrown in /app/src/Factory.php on line 144
2023-05-16 18:49:59,753 WARN exited: movary (exit status 255; not expected)
2023-05-16 18:50:00,755 INFO gave up: movary entered FATAL state, too many start retries too quickly
```
Why does it show an error about Imagick? I didn't know Movary needed that.
And why is mysql suddenly an unsupported database type?

**Comment by JVT038** [comment] 2023-05-16 18:53
My `docker-compose.yml`:
```yaml
version: "3.8"

networks:
  traefik:
    external:
      name: traefik_proxy
  

services:
  movary:
    image: leepeuker/movary:latest
    container_name: movary
    networks:
      - traefik
      - default
    environment:
      - TMDB_API_KEY=$TMDB_API_KEY
      - DATABASE_MODE="mysql"
      - DATABASE_MYSQL_HOST="mysql"
      - DATABASE_MYSQL_NAME="movary"
      - DATABASE_MYSQL_USER="movary_user"
      - DATABASE_MYSQL_PASSWORD=$MYSQL_MOVARY_PASSWORD
      - TIMEZONE=$TZ
      - APPLICATION_URL=movary.$DOMAINNAME
    volumes:
      - $DOCKERDIR/movary/storage:/app/storage
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.movary-rtr.entrypoints=https"
      - "traefik.http.routers.movary-rtr.rule=Host(`movary.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.movary-rtr.middlewares=chain-basic-lan@file"
      ## HTTP Services
      - "traefik.http.routers.movary-rtr.service=movary-svc"
      - "traefik.http.services.movary-svc.loadbalancer.server.port=80"

  mysql:
    image: mysql:8.0
    container_name: movary_mysql
    networks:
      - default
    environment:
      - MYSQL_DATABASE="movary"
      - MYSQL_USER="movary_user"
      - MYSQL_PASSWORD=$MYSQL_MOVARY_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_MOVARY_ROOT_PASSWORD
    volumes:
      - $DOCKERDIR/movary/database:/var/lib/mysql
```

**Comment by axl7777** [comment] 2023-05-17 06:11
Same here: PHP Startup: Unable to load dynamic library 'imagick.so'

**Comment by leepeuker** [comment] 2023-05-17 06:21
I get `PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so'` too, but that should no cause the container to die, it is only a warning. Movary is not using the `imagick` extension, I think the base docker image we are using probably has some configuration issue. I will try to look into it today. 

`PHP Fatal error:  Uncaught RuntimeException: Not supported database mode: "mysql" ` seems weird to me, I will try to reproduce the issue with your `docker-compose.yml`

**Comment by axl7777** [comment] 2023-05-17 06:32
I removed both containers, deleted both docker volumes, restarted and it worked for me

**Comment by leepeuker** [comment] 2023-05-17 06:33
Did the `imagick` warning vanish after you did that?

**Comment by axl7777** [comment] 2023-05-17 07:22
Nope, still there, but it works

**Comment by JVT038** [comment] 2023-05-17 14:50
You're right.
I changed my environnment to this:
```
    environment:
      - TMDB_API_KEY=$TMDB_API_KEY
      - TMDB_ENABLE_IMAGE_CACHING=1
      - DATABASE_MODE=mysql
      - DATABASE_MYSQL_HOST=mysql
      - DATABASE_MYSQL_NAME=movary
      - DATABASE_MYSQL_USER=movary_user
      - DATABASE_MYSQL_PASSWORD=$MYSQL_MOVARY_PASSWORD
      - TIMEZONE=$TZ
      - APPLICATION_URL=movary.$DOMAINNAME
```
and now the error no longer appears.
However, now this error appears:
```
2023-05-17T14:47:41.625687612Z 2023-05-17 14:47:41:625067 - Processing job...
2023-05-17T14:47:41.629373673Z [2023-05-17T16:47:41.628590+02:00] movary.ERROR: Could not process job. {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused at /app/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /app/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /app/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:33)"} []
2023-05-17T14:47:41.642205169Z 2023-05-17 14:47:41,641 WARN exited: movary (exit status 1; not expected)
```

**Comment by JVT038** [comment] 2023-05-17 14:52
> your database mode is set to "mysql"and not mysql
Still weird that the quotes make such a difference. I think it should accept mysql, 'mysql' and "mysql". Even `mysql` with backticks.
And the same applies for sqlite, 'sqlite' and "sqlite".

**Comment by JVT038** [comment] 2023-05-17 15:06
So I have found some things I want to address, because the current Docker setup makes room for a lot of issues.

1. First, Movary doesn't take a startup time of the MySQL container into account. It will try to connect instantly, but that's not possible at my machine, because it literally took 8 minutes to initialize the MySQL server. This causes the 'connection refused' errors.
2. Second, the imagick warning is weird and can cause confusion (or at least caused confusion with me)
3. Third, Movary will try to process the jobs when it's started for the first time, but that's not possible, because there is no table `movary.job_queue` if the user hasn't run the migrations yet. In this case, Movary should run migrations either automatically or it should detect that the migrations haven't been executed and show a warning to the user about that. After that, Movary should simply shut down and be manually restarted after the user has run the migrations.
4. Fourth, the issue with the quotes around the database mode. Or the lack of quotes.
5. Fifth, secrets should be possible for sensitive information such as passwords and API keys.
6. Sixth, the migrations should perform better. Currently, a single migration literally takes 15 seconds for my NAS. It can take such a long time for all of them to finish. I don't know how to improve performance though, but it should be faster, right? 

I'll create an issue for each of these things.

**Comment by leepeuker** [comment] 2023-05-17 15:15
To point 4: The application takes the string as it is saved in the environment. If someone sets `"mysql"` in the environment it is expected behavior to take the string with the quotes. There could be cases where the value should contain quotes at the beginning or end (e.g. passwords/tokens or similar). It is the responsibility of the tool/person setting the environment variables to handle quotations and not of the application I think :thinking: 

To point 6: I think that is an issue with your NAS docker/database. Migrations are executed very fast on my machines (all Ubunutu, one is running on pretty weak cloud hardware)

**Comment by leepeuker** [comment] 2023-05-18 08:58
I think we can close this ticket, because the reason the container was not starting was solved (env variable contained double quotes).

The points @JVT038 mentioned in his last comment can be discussed/solved in separate issues or in matrix.

**Closed by leepeuker** 2023-05-18 08:58 UTC
Labels: bug, priority: high
